AllCops:
  NewCops: enable

plugins:
  - rubocop-rake
  - rubocop-minitest

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
